name: Publish GitHub Pages
on:
  push:
    branches:
      - main  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish site
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Replace with the branch you want to deploy to
          FOLDER: ./  # Replace with the folder containing your website's files
